package com.example.airlinereservationsystem.controllers;

import com.example.airlinereservationsystem.DatabaseConnection;
import com.example.airlinereservationsystem.models.User;
import com.example.airlinereservationsystem.controllers.DashboardController;
import com.example.airlinereservationsystem.controllers.StaffController;
import com.example.airlinereservationsystem.controllers.CustomerController;
import javafx.collections.FXCollections;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

public class LoginController {
    private static final Logger LOGGER = Logger.getLogger(LoginController.class.getName());

    @FXML private VBox loginForm;
    @FXML private VBox registerForm;
    @FXML private TextField usernameField;
    @FXML private PasswordField passwordField;
    @FXML private TextField regUsernameField;
    @FXML private PasswordField regPasswordField;
    @FXML private TextField regFullNameField;
    @FXML private ComboBox<String> regRoleCombo;
    @FXML private Label statusLabel;

    private static User currentUser;

    @FXML
    public void initialize() {
        try {
            setupDefaultUsers();
            regRoleCombo.setItems(FXCollections.observableArrayList("Customer", "Staff", "Admin"));
            regRoleCombo.setValue("Customer");
        } catch (Exception e) {
            LOGGER.log(Level.SEVERE, "Failed to initialize login controller", e);
        }
    }

    private void setupDefaultUsers() {
        String createTableSQL = """
            CREATE TABLE IF NOT EXISTS users (
                user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) UNIQUE NOT NULL,
                password VARCHAR(100) NOT NULL,
                full_name VARCHAR(100) NOT NULL,
                role VARCHAR(20) NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """;

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement createStmt = conn.prepareStatement(createTableSQL)) {
            createStmt.execute();

            // Insert default users safely
            insertUserIfNotExists(conn, "admin", "admin123", "System Administrator", "Admin");
            insertUserIfNotExists(conn, "staff", "staff123", "Airline Staff", "Staff");
            insertUserIfNotExists(conn, "customer", "customer123", "Sample Customer", "Customer");

        } catch (Exception e) {
            LOGGER.log(Level.WARNING, "Failed to setup default users", e);
        }
    }

    private void insertUserIfNotExists(Connection conn, String username, String password, String fullName, String role) {
        String checkSQL = "SELECT COUNT(*) FROM users WHERE username = ?";
        String insertSQL = "INSERT INTO users (username, password, full_name, role) VALUES (?, ?, ?, ?)";
        try (PreparedStatement checkStmt = conn.prepareStatement(checkSQL)) {
            checkStmt.setString(1, username);
            ResultSet rs = checkStmt.executeQuery();
            if (rs.next() && rs.getInt(1) == 0) {
                try (PreparedStatement insertStmt = conn.prepareStatement(insertSQL)) {
                    insertStmt.setString(1, username);
                    insertStmt.setString(2, password);
                    insertStmt.setString(3, fullName);
                    insertStmt.setString(4, role);
                    insertStmt.executeUpdate();
                }
            }
        } catch (Exception e) {
            LOGGER.log(Level.WARNING, "Failed to insert default user: " + username, e);
        }
    }

    @FXML
    protected void onLogin(ActionEvent event) {
        try {
            String username = usernameField.getText().trim();
            String password = passwordField.getText();

            if (username.isEmpty() || password.isEmpty()) {
                statusLabel.setText("⚠️ Please enter username and password");
                return;
            }

            User user = authenticateUser(username, password);
            if (user != null) {
                currentUser = user;
                statusLabel.setText("✅ Login successful!");
                navigateToDashboard();
            } else {
                statusLabel.setText("❌ Invalid username or password");
            }

        } catch (Exception e) {
            LOGGER.log(Level.SEVERE, "Login failed", e);
            statusLabel.setText("❌ Login error: " + e.getMessage());
        }
    }

    @FXML
    protected void onRegister(ActionEvent event) {
        try {
            String username = regUsernameField.getText().trim();
            String password = regPasswordField.getText();
            String fullName = regFullNameField.getText().trim();
            String role = regRoleCombo.getValue();

            if (username.isEmpty() || password.isEmpty() || fullName.isEmpty() || role == null) {
                statusLabel.setText("⚠️ Please fill all fields");
                return;
            }

            if (registerUser(username, password, fullName, role)) {
                statusLabel.setText("✅ Account created successfully!");
                clearRegisterFields();
                showLogin(null);
            } else {
                statusLabel.setText("❌ Username already exists");
            }

        } catch (Exception e) {
            LOGGER.log(Level.SEVERE, "Registration failed", e);
            statusLabel.setText("❌ Registration error: " + e.getMessage());
        }
    }

    @FXML
    protected void showRegister(ActionEvent event) {
        loginForm.setVisible(false);
        loginForm.setManaged(false);
        registerForm.setVisible(true);
        registerForm.setManaged(true);
        statusLabel.setText("");
    }

    @FXML
    protected void showLogin(ActionEvent event) {
        registerForm.setVisible(false);
        registerForm.setManaged(false);
        loginForm.setVisible(true);
        loginForm.setManaged(true);
        statusLabel.setText("");
    }

    private User authenticateUser(String username, String password) {
        String query = "SELECT * FROM users WHERE username = ? AND password = ?";
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(query)) {
            ps.setString(1, username);
            ps.setString(2, password);

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return new User(
                            rs.getInt("user_id"),
                            rs.getString("username"),
                            rs.getString("full_name"),
                            rs.getString("role")
                    );
                }
            }
        } catch (Exception e) {
            LOGGER.log(Level.SEVERE, "Authentication failed", e);
        }
        return null;
    }

    private boolean registerUser(String username, String password, String fullName, String role) {
        try (Connection conn = DatabaseConnection.getConnection()) {
            String query = "INSERT INTO users (username, password, full_name, role) VALUES (?, ?, ?, ?)";
            try (PreparedStatement ps = conn.prepareStatement(query)) {
                ps.setString(1, username);
                ps.setString(2, password);
                ps.setString(3, fullName);
                ps.setString(4, role);
                return ps.executeUpdate() > 0;
            }
        } catch (Exception e) {
            LOGGER.log(Level.WARNING, "Registration failed", e);
            return false;
        }
    }

    private void navigateToDashboard() {
        try {
            String fxmlFile;
            String title;
            
            // Determine which dashboard to open based on user role
            if (currentUser.isAdmin()) {
                fxmlFile = "/com/example/airlinereservationsystem/dashboard.fxml";
                title = "✈️ Airline System - Admin Dashboard";
            } else if (currentUser.isStaff()) {
                fxmlFile = "/com/example/airlinereservationsystem/staff.fxml";
                title = "✈️ Airline System - Staff Dashboard";
            } else {
                fxmlFile = "/com/example/airlinereservationsystem/customer.fxml";
                title = "✈️ Airline System - Customer Portal";
            }
            
            FXMLLoader loader = new FXMLLoader(getClass().getResource(fxmlFile));
            Scene scene = new Scene(loader.load(), 1200, 800);
            
            // Set the current user in the appropriate controller
            Object controller = loader.getController();
            if (controller instanceof DashboardController) {
                ((DashboardController) controller).setCurrentUser(currentUser);
            } else if (controller instanceof StaffController) {
                ((StaffController) controller).setCurrentUser(currentUser);
            } else if (controller instanceof CustomerController) {
                ((CustomerController) controller).setCurrentUser(currentUser);
            }
            
            Stage stage = (Stage) usernameField.getScene().getWindow();
            stage.setScene(scene);
            stage.setTitle(title + " - " + currentUser.getFullName());

        } catch (Exception e) {
            LOGGER.log(Level.SEVERE, "Failed to navigate to dashboard", e);
            statusLabel.setText("❌ Error loading dashboard");
        }
    }

    private void clearRegisterFields() {
        regUsernameField.clear();
        regPasswordField.clear();
        regFullNameField.clear();
        regRoleCombo.setValue("Customer");
    }

    public static User getCurrentUser() {
        return currentUser;
    }
}