package com.example.airlinereservationsystem;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import static com.example.airlinereservationsystem.Main.LOGGER;

public final class DatabaseConnection {
    private static final String URL = "jdbc:postgresql://dpg-d4gd9s9r0fns738c749g-a.oregon-postgres.render.com:5432/airline_reservation";
    private static final String USER = "new_user";
    private static final String PASSWORD = "gnjqdk8vU6Y61yTYgrisx0HOHnObPckA";


    private static Connection connection;

    private DatabaseConnection() { }

    public static Connection getConnection() throws SQLException {
        try {
            if (connection == null || connection.isClosed()) {
                try {
                    Class.forName("org.postgresql.Driver");
                    connection = DriverManager.getConnection(
                            "jdbc:postgresql://dpg-d4gd9s9r0fns738c749g-a.oregon-postgres.render.com:5432/airline_reservation?sslmode=require",
                            "new_user",
                            "gnjqdk8vU6Y61yTYgrisx0HOHnObPckA"
                    );
                    LOGGER.info("Connected to Remote PostgreSQL Database Successfully!");

                } catch (Exception e) {
                    LOGGER.info("PostgreSQL unavailable, using H2 demo database");
                    Class.forName("org.h2.Driver");
                    connection = DriverManager.getConnection(
                            "jdbc:h2:mem:demo;MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
                    LOGGER.info("H2 demo database connected");
                }
            }
            return connection;
        } catch (Exception e) {
            throw new SQLException("Database connection failed: " + e.getMessage(), e);
        }
    }

    public static void closeConnection() {
        try {
            if (connection != null && !connection.isClosed()) {
                connection.close();
                LOGGER.info("Database connection closed successfully");
            }
        } catch (SQLException e) {
            LOGGER.log(Level.WARNING, "Error closing database connection", e);
        }
    }

    public static void setupDatabase() throws SQLException {
        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {

            LOGGER.info("Starting database setup...");

            // Users table (compatible with both PostgreSQL and H2)
            stmt.executeUpdate("""
                CREATE TABLE IF NOT EXISTS users (
                    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(50) UNIQUE NOT NULL,
                    password VARCHAR(100) NOT NULL,
                    full_name VARCHAR(100) NOT NULL,
                    role VARCHAR(20) NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """);

            // Customers table
            stmt.executeUpdate("""
                CREATE TABLE IF NOT EXISTS customers (
                    cust_id SERIAL PRIMARY KEY,
                    cust_name TEXT NOT NULL,
                    father_name TEXT,
                    gender TEXT,
                    dob DATE,
                    address TEXT,
                    tel_no TEXT,
                    profession TEXT,
                    concession TEXT
                )
            """);

            // Fleet table
            stmt.executeUpdate("""
                CREATE TABLE IF NOT EXISTS fleet (
                    fleet_id SERIAL PRIMARY KEY,
                    no_aircraft TEXT,
                    club_pre_capacity INT,
                    eco_capacity INT,
                    engine_type TEXT,
                    cruise_speed TEXT,
                    air_length TEXT,
                    wing_span TEXT
                )
            """);

            // Flights table
            stmt.executeUpdate("""
                CREATE TABLE IF NOT EXISTS flights (
                    flight_code SERIAL PRIMARY KEY,
                    flight_name TEXT NOT NULL,
                    class_code TEXT,
                    total_eco_seats INT,
                    total_exe_seats INT,
                    fleet_id INT REFERENCES fleet(fleet_id)
                )
            """);

            // Fare table
            stmt.executeUpdate("""
                CREATE TABLE IF NOT EXISTS fare (
                    fare_id SERIAL PRIMARY KEY,
                    route_code TEXT,
                    source_place TEXT,
                    via TEXT,
                    dest_place TEXT,
                    depart_time TIMESTAMP,
                    arrival_time TIMESTAMP,
                    flight_code INT REFERENCES flights(flight_code),
                    class_code TEXT,
                    fare NUMERIC(10,2)
                )
            """);

            // Customer details table (updated)
            stmt.executeUpdate("""
                CREATE TABLE IF NOT EXISTS customer_details (
                    cust_id SERIAL PRIMARY KEY,
                    cust_name VARCHAR(100) NOT NULL,
                    father_name VARCHAR(100),
                    gender VARCHAR(10),
                    dob DATE,
                    address TEXT,
                    tel_no VARCHAR(20),
                    profession VARCHAR(50),
                    security VARCHAR(50),
                    concession VARCHAR(30),
                    travel_date DATE
                )
            """);
            
            // Reservations table (updated)
            stmt.executeUpdate("""
                CREATE TABLE IF NOT EXISTS reservations (
                    reservation_id SERIAL PRIMARY KEY,
                    cust_id INT REFERENCES customer_details(cust_id),
                    flight_code INT REFERENCES flights(flight_code),
                    seat_class VARCHAR(10),
                    seat_number INT,
                    status VARCHAR(20),
                    fare DECIMAL(10,2),
                    travel_date DATE,
                    pnr VARCHAR(20)
                )
            """);

            // Cancellations table (updated)
            stmt.executeUpdate("""
                CREATE TABLE IF NOT EXISTS cancellations (
                    cancel_id SERIAL PRIMARY KEY,
                    reservation_id INT REFERENCES reservations(reservation_id),
                    cancel_date DATE,
                    refund_amount DECIMAL(10,2),
                    cancellation_fee DECIMAL(10,2)
                )
            """);

            // Waiting list table
            stmt.executeUpdate("""
                CREATE TABLE IF NOT EXISTS waiting_list (
                    wait_id SERIAL PRIMARY KEY,
                    flight_code INT REFERENCES flights(flight_code),
                    cust_id INT REFERENCES customers(cust_id),
                    seat_class TEXT,
                    waiting_no INT,
                    travel_date DATE
                )
            """);

            insertSampleData(conn);
            LOGGER.info("Database setup completed successfully!");

        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Database setup failed", e);
            throw new SQLException("Failed to setup database: " + e.getMessage(), e);
        }
    }

    private static void insertSampleData(Connection conn) {
        try {
            // Check and insert flights
            String checkFlights = "SELECT COUNT(*) FROM flights";
            try (PreparedStatement ps = conn.prepareStatement(checkFlights);
                 ResultSet rs = ps.executeQuery()) {
                if (rs.next() && rs.getInt(1) == 0) {
                    String insertFlight = "INSERT INTO flights (flight_name, class_code, total_eco_seats, total_exe_seats) VALUES (?, ?, ?, ?)";
                    try (PreparedStatement insertPs = conn.prepareStatement(insertFlight)) { // Renamed to avoid conflict
                        String[][] flightsData = {{"Lesotho101", "BOTH", "150", "30"}, {"Maluti102", "BOTH", "180", "20"}, {"Basotho103", "ECO", "200", "0"}, {"Mohale104", "BOTH", "160", "40"}, {"Katse105", "BOTH", "140", "25"}};
                        for (String[] flight : flightsData) {
                            insertPs.setString(1, flight[0]);
                            insertPs.setString(2, flight[1]);
                            insertPs.setInt(3, Integer.parseInt(flight[2]));
                            insertPs.setInt(4, Integer.parseInt(flight[3]));
                            insertPs.executeUpdate();
                        }
                        LOGGER.info("Sample flight data inserted successfully.");
                    }
                }
            }

            // Check and insert customers
            String checkCustomers = "SELECT COUNT(*) FROM customer_details";
            try (PreparedStatement ps = conn.prepareStatement(checkCustomers);
                 ResultSet rs = ps.executeQuery()) {
                if (rs.next() && rs.getInt(1) == 0) {
                    String insertCustomer = "INSERT INTO customer_details (cust_name, gender, concession, tel_no) VALUES (?, ?, ?, ?)";
                    try (PreparedStatement insertPs = conn.prepareStatement(insertCustomer)) {
                        String[][] customersData = {
                            {"Thabo Monne", "Male", "None", "+266-5888-1001"},
                            {"Lineo Taki", "Female", "Student", "+266-5888-1002"},
                            {"Mpho Sekhonyana", "Male", "Senior Citizen", "+266-5888-1003"},
                            {"Palesa Mokoena", "Female", "None", "+266-5888-1004"},
                            {"Thabiso Molefe", "Male", "Cancer Patient", "+266-5888-1005"},
                            {"Mamello Ntšo", "Female", "Student", "+266-5888-1006"},
                            {"Lebohang Khiba", "Male", "None", "+266-5888-1007"},
                            {"Refiloe Mofokeng", "Female", "Senior Citizen", "+266-5888-1008"}
                        };
                        for (String[] customer : customersData) {
                            insertPs.setString(1, customer[0]);
                            insertPs.setString(2, customer[1]);
                            insertPs.setString(3, customer[2]);
                            insertPs.setString(4, customer[3]);
                            insertPs.executeUpdate();
                        }
                        LOGGER.info("Sample customer data inserted successfully.");
                    }
                }
            }

            // Check and insert sample reservations
            String checkReservations = "SELECT COUNT(*) FROM reservations";
            try (PreparedStatement ps = conn.prepareStatement(checkReservations);
                 ResultSet rs = ps.executeQuery()) {
                if (rs.next() && rs.getInt(1) == 0) {
                    String insertReservation = "INSERT INTO reservations (cust_id, flight_code, seat_class, seat_number, status, fare, travel_date, pnr) VALUES (?, ?, ?, ?, ?, ?, CURRENT_DATE, ?)";
                    try (PreparedStatement insertPs = conn.prepareStatement(insertReservation)) {
                        Object[][] reservationsData = {
                            {1, 1, "Economy", 22, "Confirmed", 850.0, "PNR001"},
                            {2, 2, "Business", 5, "Confirmed", 2040.0, "PNR002"},
                            {3, 3, "Economy", 101, "Waiting", 850.0, "PNR003"},
                            {4, 4, "Business", 1, "Confirmed", 2040.0, "PNR004"},
                            {5, 5, "Economy", 54, "Confirmed", 850.0, "PNR005"}
                        };
                        for (Object[] res : reservationsData) {
                            insertPs.setInt(1, (Integer) res[0]);
                            insertPs.setInt(2, (Integer) res[1]);
                            insertPs.setString(3, (String) res[2]);
                            insertPs.setInt(4, (Integer) res[3]);
                            insertPs.setString(5, (String) res[4]);
                            insertPs.setDouble(6, (Double) res[5]);
                            insertPs.setString(7, (String) res[6]);
                            insertPs.executeUpdate();
                        }
                        LOGGER.info("Sample reservation data inserted successfully.");
                    }
                }
            }
            
            // Check and insert sample fare data
            String checkFare = "SELECT COUNT(*) FROM fare";
            try (PreparedStatement ps = conn.prepareStatement(checkFare);
                 ResultSet rs = ps.executeQuery()) {
                if (rs.next() && rs.getInt(1) == 0) {
                    String insertFare = "INSERT INTO fare (route_code, source_place, dest_place, depart_time, arrival_time, flight_code, class_code, fare) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                    try (PreparedStatement insertPs = conn.prepareStatement(insertFare)) {
                        Object[][] fareData = {
                            {"RT001", "Maseru", "Johannesburg", "09:00:00", "11:30:00", 1, "Economy", 850.0},
                            {"RT001B", "Maseru", "Johannesburg", "09:00:00", "11:30:00", 1, "Business", 2040.0},
                            {"RT002", "Maseru", "Johannesburg", "14:00:00", "16:30:00", 2, "Economy", 900.0},
                            {"RT002B", "Maseru", "Johannesburg", "14:00:00", "16:30:00", 2, "Business", 2150.0},
                            {"RT003", "Maseru", "Cape Town", "08:00:00", "12:00:00", 3, "Economy", 1200.0},
                            {"RT004", "Maseru", "Durban", "10:30:00", "13:45:00", 4, "Economy", 1100.0},
                            {"RT004B", "Maseru", "Durban", "10:30:00", "13:45:00", 4, "Business", 2500.0},
                            {"RT005", "Maseru", "Bloemfontein", "16:00:00", "17:15:00", 5, "Economy", 650.0},
                            {"RT006", "Johannesburg", "Maseru", "18:00:00", "20:30:00", 1, "Economy", 850.0},
                            {"RT007", "Cape Town", "Maseru", "15:00:00", "19:00:00", 3, "Economy", 1200.0},
                            {"RT008", "Durban", "Maseru", "12:00:00", "15:15:00", 4, "Economy", 1100.0}
                        };
                        for (Object[] fare : fareData) {
                            insertPs.setString(1, (String) fare[0]);
                            insertPs.setString(2, (String) fare[1]);
                            insertPs.setString(3, (String) fare[2]);
                            insertPs.setTime(4, Time.valueOf((String) fare[3]));
                            insertPs.setTime(5, Time.valueOf((String) fare[4]));
                            insertPs.setInt(6, (Integer) fare[5]);
                            insertPs.setString(7, (String) fare[6]);
                            insertPs.setDouble(8, (Double) fare[7]);
                            insertPs.executeUpdate();
                        }
                        LOGGER.info("Sample fare data inserted successfully.");
                    }
                }
            }
        } catch (SQLException e) {
            LOGGER.log(Level.WARNING, "Failed to insert sample data", e);
        }
    }
}